
SELECT_PRO = "SELECT * FROM projects;"
DELETE_PRO = "DELETE FROM projects WHERE id = ?;"

INSERT_PRO = ("INSERT INTO projects ("
              "title, "
              "category, "
              "type, "
              "creative_skills, "
              "technical_skills, "
              "tools, "
              "status, "
              "duration, "
              "collaborators, "
              "languages, "
              "notes, "
              "report_done, "
              "added_to_portfolio, "
              "has_showcase_material) "
              "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"
            )

UPDATE_PRO = ("UPDATE projects SET "
              "title = ?, "
              "category = ?, "
              "type = ?, "
              "creative_skills = ?, "
              "technical_skills = ?, "
              "tools = ?, "
              "status = ?, "
              "duration = ?, "
              "collaborators = ?, "
              "languages = ?, "
              "report_done = ?, "
              "added_to_portfolio = ?, "
              "has_showcase_material = ?, "
              "notes = ? "
              "WHERE id = ?;"
            )
